# 服务设置
server:
  port: 9999

# 容器设置
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由注册
          enabled: true
      routes:
        - id: cloud-study-of-consumer
          uri: lb://cloud-study-of-consumer
          predicates:
            - Path=/consumer/**


  application:
    name: cloud-study-gateway

eureka:
  client:
    # true表示向注册中心注册服务
    register-with-eureka: true
    # 是否向注册中心抓取已有的注册信息，默认为true。集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-01:1205/eureka
  instance:
    instance-id: cloud-study-gateway
    prefer-ip-address: true
