# 服务设置
server:
  port: 81
  servlet:
    context-path: /consumer

# 容器设置
spring:
  application:
    name: cloud-study-of-consumer

eureka:
  client:
    # true表示向注册中心注册服务
    register-with-eureka: true
    # 是否向注册中心抓取已有的注册信息，默认为true。集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-03:1207/eureka
  instance:
    instance-id: cloud-study-of-consumer
    prefer-ip-address: true

# feign配置
feign:
  compression:
    request:
      # 启用数据压缩
      enabled: true
      # 压缩数据类型
      mime-types: text/xml,application/xml,application/json
      # 数据压缩下限,2048标识传输数据大于2048字节时会进行压缩(默认2048)
      min-request-size: 2048
    # 启用数据压缩响应
    response:
      enabled: true
  httpclient:
    # 禁用httpClient
    enabled: false
  okhttp:
    # 启用OKHttp
    enabled: true
#
#ribbon:
#  # 建立连接所用的时间适用于网络正常情况下两端连接所用的时间
#  ReadTimeout: 5000
#  # 建立连接后从服务区读取到可用资源所用的时间
#  ConnectTimeout: 5000

# 日志配置
logging:
  level:
    # 服务客户端适用debug级别,这样才能打印Feign的自身级别日志
    com.pcocoon.of.consumer.client.*: debug



